### ISSUE TITLE
Squadbot responds to messages in different groups/convos

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#1]
This would require some changes in the API to fix.

We shoukd talk about this with the team.

**Comment by boltgolt** [comment]
That will make the api a lot more complicated though

**Comment by Nickforall** [comment]
`message` -> `if raw.groupid == settings.group_id`
`privateMessage` if raw.groupid != undefined

I was thinking about doing it like this. and maybe add the posibility to do `bot.send(string, phone)`

**Comment by boltgolt** [comment]
sounds good to me

**Comment by boltgolt** [comment]
Implementing as `bot.private`, so everything in the API is the same. The only difference to the groupchat api is that you call `bot.private.something()` in stead of  `bot.something()`.

**Comment by Boltgolt** [comment]
Wrong button

**Comment by boltgolt** [comment]
Fully implemented in 0561d267c1d24d9b0bda698c25ceecfd08a64d30
