### ISSUE TITLE
Someone clean up that readme

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#10]
I am lazy

DANIEL, JUST DO IT!

**Comment by danielmizrachi** [comment]
@Nickforall Y'all need to tag me! I was looking at it last week and wondering if someone was going to do something. I'll do it tonight.

**Comment by boltgolt** [comment]
you were assigned

**Comment by Nickforall** [comment]
I assigned you since you said you liked writing documentation and stuff

**Comment by danielmizrachi** [comment]
Done, except for the new "What is Squadbot" section that I think should be included (just a quick summary). I had no idea where to start so you can write it or decide it's not necessary.

**Comment by Nickforall** [comment]
@dannyboy49 I would appreciate if you could do a small spell/grammar-check on my writing before we close this issue.
