### ISSUE TITLE
Improve global print() with more colors

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#11]
maybe find a library for it?

**Comment by boltgolt** [comment]
Its based on special characters, i have a list of colors somewhere.

**Comment by Nickforall** [comment]
perhaps a non-api `parsecolor` function that converts strings into those characters?

Or have logging levels, such as warning, info, error, fatal, success that have their own colors.

**Comment by boltgolt** [comment]
There are a lot of colors you can use now, and the style can even be changed (bold, underline, etc)
