### ISSUE TITLE
Arguments in command event should be in lowercase too

### ISSUE THREAD

**Issue by Nickforall** [ABitOfSquad/squadbot#5]
Just like the cmd variable, it would save some time and code for plugin devs to have those in lowercase too.

**Comment by boltgolt** [comment]
Would make commands as /say impossible though, you would need to use meta to get it properly capitalised, and parse that  yourself.

**Comment by Nickforall** [comment]
Hmmm good point.

**Comment by Nickforall** [comment]
Closed. Not implemented.
